<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{cda09ef7-7100-4d20-8a2f-028dec4c33fa}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	_ST80a		: ST80a;
	_ST80b		: sT80b; 
	_ST80c		: ST80c; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>