<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ST80c" Id="{6511e522-115d-43cb-a766-5883ce869da5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ST80c
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ST80c">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>