<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="sT80b" Id="{3cf6e9b3-e801-41fd-874b-1d437fea11c0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK sT80b
VAR
	_promenlivataNaFilip : BOOL;
	_test : BOOL; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="_test" Id="{4a5b8f54-185c-4781-84cc-cdd5f85a1e98}">
      <Declaration><![CDATA[METHOD PROTECTED _test
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_promenlivataNaFilip:= TRUE;
_test:= FALSE;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="sT80b">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="sT80b._test">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>