<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ST80a" Id="{ebc57cc3-e53c-4a10-a66c-718a2d623872}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ST80a
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ST80a">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>